/* DREAM GARAGE / VANILLA JS */
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const vehicleImages={side:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1400&q=85',front:'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1400&q=85',rear:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=85',interior:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85'};
const collectionVehicles=[{model:'DG 911R',category:'PURE PERFORMANCE',hp:'518 HP',accel:'3.2 SEC',price:'€ 184,900',image:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1500&q=85'},{model:'DG V12',category:'GRAND TOURING',hp:'740 HP',accel:'2.9 SEC',price:'€ 294,500',image:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85'},{model:'DG GT-X',category:'TRACK BRED',hp:'612 HP',accel:'3.0 SEC',price:'€ 238,900',image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=85'}];
const colors=[['obsidian','Obsidian Black','#14171b'],['arctic','Arctic White','#d9d9d4'],['orange','Performance Orange','#d95d30'],['emerald','Deep Emerald','#164b3c'],['silver','Titanium Silver','#858b8f'],['blue','Midnight Blue','#172b4c']];
const options={wheels:[['forged19','19” Forged','€ 0'],['carbon20','20” Carbon','€ 8,500'],['aero21','21” Aero','€ 12,500']],brakes:[['steel','Steel Performance','€ 0'],['ceramic','Carbon Ceramic','€ 6,800'],['pro','Carbon Ceramic Pro','€ 11,200']],interior:[['black-leather','Black Leather','€ 0'],['ivory-leather','Ivory Leather','€ 2,400'],['alcantara','Alcantara','€ 4,800'],['carbon-sport','Carbon Sport','€ 7,200']]};
const prices={wheels:{forged19:0,carbon20:8500,aero21:12500},interior:{'black-leather':0,'ivory-leather':2400,alcantara:4800,'carbon-sport':7200},brakes:{steel:0,ceramic:6800,pro:11200}};
const defaults={exterior:'obsidian',wheels:'forged19',brakes:'steel',interior:'black-leather',trackPackage:false,aeroPackage:false,lightweightPackage:false};
let carState={...defaults}; let toastTimer;
// Loading
let load=0;const loaderTimer=setInterval(()=>{load+=Math.floor(Math.random()*16)+8;if(load>=100){load=100;clearInterval(loaderTimer);setTimeout(()=>$('#loader').classList.add('done'),250)}$('#loaderBar').style.width=load+'%';$('#loaderPercent').textContent=load+'%'},100);
// Navigation
function closeMobile(){$('#mobileMenu').classList.remove('open');document.body.classList.remove('menu-open')}
$('#menuToggle').addEventListener('click',()=>{$('#mobileMenu').classList.add('open');document.body.classList.add('menu-open')});$('#menuClose').addEventListener('click',closeMobile);$$('.mobile-menu a').forEach(a=>a.addEventListener('click',closeMobile));
window.addEventListener('scroll',()=>{$('#siteHeader').classList.toggle('scrolled',scrollY>40);$('.scroll-cue').classList.toggle('hide',scrollY>80);const y=scrollY+innerHeight*.35;$$('main section[id]').forEach(s=>{if(y>=s.offsetTop&&y<s.offsetTop+s.offsetHeight){$$('.nav-link').forEach(n=>n.classList.toggle('active',n.getAttribute('href')==='#'+s.id))}});const im=$('.immersive-image');if(im){const r=im.parentElement.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0)im.style.transform=`scale(${1.05+Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height)))*.08})`}}, {passive:true});
// Scroll effects and counters
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.classList.contains('stat-grid'))$$('.stat-number',e.target).forEach(countUp);if(e.target.id==='performanceGraph')e.target.parentElement.classList.add('visible');io.unobserve(e.target)}}),{threshold:.15});$$('.reveal,.stat-grid,#performanceGraph').forEach(e=>io.observe(e));
function countUp(el){if(el.dataset.done)return;el.dataset.done='1';const target=+el.dataset.count||+el.dataset.target,dec=+(el.dataset.decimals||0),start=performance.now();function tick(now){const p=Math.min(1,(now-start)/1100),v=target*(1-Math.pow(1-p,3));el.textContent=v.toFixed(dec);if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
$$('.ticker').forEach(e=>setTimeout(()=>countUp(e),450));
// Collection / carousel
function renderCollection(){const grid=$('#collectionGrid');grid.innerHTML=collectionVehicles.map((v,i)=>`<article class="vehicle-card" data-index="${i}" data-image="${v.image}"><div class="vehicle-card__image" style="background-image:url('${v.image}')"></div><button class="heart" data-model="${v.model}" aria-label="Add ${v.model} to favorites">♡</button><div class="vehicle-card__content"><div><small>${v.category}</small><h3>${v.model}</h3><div class="vehicle-card__stats"><span>${v.hp}</span><span>${v.accel}</span><span>${v.price}</span></div></div><b class="card-arrow">↗</b></div></article>`).join('');updateFavoriteUI();$$('.vehicle-card').forEach(c=>c.addEventListener('click',e=>{if(!e.target.closest('.heart'))openViewer(+c.dataset.index)}));$$('.heart').forEach(h=>h.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(h.dataset.model)}));$('#carouselDots').innerHTML=collectionVehicles.map((_,i)=>`<i class="${i===0?'active':''}"></i>`).join('')}
let carouselIndex=0;function carouselMove(dir){carouselIndex=(carouselIndex+dir+3)%3;const cards=$$('.vehicle-card');if(innerWidth<=700)cards[carouselIndex].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});else{$('#collectionGrid').style.transform=`translateX(${-carouselIndex*8}px)`}$$('#carouselDots i').forEach((d,i)=>d.classList.toggle('active',i===carouselIndex))}$('#prevCar').addEventListener('click',()=>carouselMove(-1));$('#nextCar').addEventListener('click',()=>carouselMove(1));renderCollection();
// Configurator
function loadConfiguration(){try{const saved=JSON.parse(localStorage.getItem('dreamGarageConfig'));if(saved)carState={...defaults,...saved}}catch(e){}}
function saveConfiguration(){localStorage.setItem('dreamGarageConfig',JSON.stringify({...carState,totalPrice:calculate().total}))}
function calculate(){let opts=prices.wheels[carState.wheels]+prices.brakes[carState.brakes]+prices.interior[carState.interior];if(carState.trackPackage)opts+=9800;if(carState.aeroPackage)opts+=7600;if(carState.lightweightPackage)opts+=12400;return{opts,total:184900+opts,power:518+(carState.trackPackage?12:0),weight:1450-(carState.lightweightPackage?32:0),accel:3.2-(carState.trackPackage?.2:0)-(carState.aeroPackage?.1:0),speed:296+(carState.aeroPackage?6:0)}}
function money(n){return'€ '+Math.round(n).toLocaleString('de-DE')}
function updatePrice(){const c=calculate();animateText($('#totalPrice'),money(c.total));$('#optionsPrice').textContent='OPTIONS / '+money(c.opts);$('#powerValue').innerHTML=`${c.power} <i>HP</i>`;$('#weightValue').innerHTML=`${c.weight} <i>KG</i>`;$('#accelValue').innerHTML=`${c.accel.toFixed(1)} <i>SEC</i>`;$('#speedValue').innerHTML=`${c.speed} <i>KM/H</i>`}
function animateText(el,text){el.animate([{opacity:.25,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:350,easing:'ease-out'});el.textContent=text}
function updateVehiclePreview(){const p=$('#carPreview');p.dataset.color=carState.exterior;p.dataset.wheels=carState.wheels;$('#caliper').style.background=carState.brakes==='steel'?'#e86f3d':carState.brakes==='ceramic'?'#e8c66a':'#e36b6b'}
function updateConfigurator(){updateVehiclePreview();updatePrice();$$('.swatch').forEach(x=>x.classList.toggle('active',x.dataset.value===carState.exterior));$$('.option').forEach(x=>x.classList.toggle('active',x.dataset.value===carState[x.dataset.type]));$('#trackPackage').checked=carState.trackPackage;$('#aeroPackage').checked=carState.aeroPackage;$('#lightweightPackage').checked=carState.lightweightPackage;saveConfiguration()}
function makeOptions(){const sw=$('#colorOptions');sw.innerHTML=colors.map(c=>`<button class="swatch" data-value="${c[0]}" style="--swatch:${c[2]}" aria-label="${c[1]}"><span>${c[1]}</span></button>`).join('');sw.addEventListener('click',e=>{const b=e.target.closest('.swatch');if(!b)return;carState.exterior=b.dataset.value;updateConfigurator();showToast('Configuration updated',b.querySelector('span').textContent)});for(const type of ['wheels','brakes','interior']){$('#'+type+'Options').innerHTML=options[type].map(o=>`<button class="option" data-type="${type}" data-value="${o[0]}"><span>${o[1]}</span><small>${o[2]}</small></button>`).join('');$('#'+type+'Options').addEventListener('click',e=>{const b=e.target.closest('.option');if(!b)return;carState[type]=b.dataset.value;updateConfigurator();showToast('Configuration updated',b.querySelector('span').textContent)})}}
loadConfiguration();makeOptions();['trackPackage','aeroPackage','lightweightPackage'].forEach(id=>$('#'+id).addEventListener('change',e=>{carState[id]=e.target.checked;updateConfigurator();showToast(e.target.checked?id.replace('Package',' Package')+' enabled':'Configuration updated')}));updateConfigurator();
$$('.config-tab').forEach(t=>t.addEventListener('click',()=>{const tab=t.dataset.tab;$$('.config-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelector(`[data-panel="${tab}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}));
$('#resetConfig').addEventListener('click',()=>{carState={...defaults};updateConfigurator();showToast('Configuration reset','Your DG-911R is back to its original specification.')});$('#saveBuild').addEventListener('click',()=>{saveConfiguration();showToast('Build saved','Your configuration is stored on this device.')});
// Vehicle views and viewer
$$('.view-btn').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;$$('.view-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#carImage').style.opacity=0;setTimeout(()=>{$('#carImage').style.backgroundImage=`url('${vehicleImages[v]}')`;$('#carImage').style.opacity=1},220)}));
let viewerIndex=0;function openViewer(i=0){viewerIndex=i;$('#viewerModal').classList.add('open');$('#viewerModal').setAttribute('aria-hidden','false');updateViewer();document.body.style.overflow='hidden'}function closeModal(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true');if(!$('.modal.open')&&!$('#searchOverlay').classList.contains('open'))document.body.style.overflow=''}function updateViewer(){const v=collectionVehicles[viewerIndex];$('#viewerImage').style.backgroundImage=`url('${v.image}')`;$('#viewerInfo')?.remove();$('#viewerModal h2').innerHTML=`${v.model}<br><em>${v.category}.</em>`;$('#viewerView').textContent=v.category}$('#expandView').addEventListener('click',()=>openViewer());$('#viewerPrev').addEventListener('click',()=>{viewerIndex=(viewerIndex+2)%3;updateViewer()});$('#viewerNext').addEventListener('click',()=>{viewerIndex=(viewerIndex+1)%3;updateViewer()});$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));$$('.modal__backdrop').forEach(b=>b.addEventListener('click',()=>closeModal(b.parentElement.id)));
// Drive form
$('#driveBtn').addEventListener('click',()=>{$('#driveModal').classList.add('open');$('#driveModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'});$('#driveForm').addEventListener('submit',e=>{e.preventDefault();$('#formContent').innerHTML='<div class="success-state"><p class="eyebrow">REQUEST RECEIVED / 009</p><h2>THE ROAD<br>AWAITS <em>YOU.</em></h2><p>Our concierge team will contact you shortly.</p><button class="button" onclick="closeModal(\'driveModal\')">CLOSE <span>↗</span></button></div>';showToast('Request received','Our concierge team will contact you shortly.')});
// Search
$('#searchBtn').addEventListener('click',()=>{$('#searchOverlay').classList.add('open');$('#searchInput').focus();document.body.style.overflow='hidden'});$('#searchClose').addEventListener('click',()=>{ $('#searchOverlay').classList.remove('open');document.body.style.overflow=''});$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>{$('#searchInput').value=b.textContent;renderSearch(b.textContent)}));$('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));function renderSearch(q){const results=q?['DG 911R / Pure performance','Active Aerodynamics / Technology','The Science of Speed / Journal'].filter(x=>x.toLowerCase().includes(q.toLowerCase())||q.length<2):[];$('#searchResults').innerHTML=results.map(r=>`<div>↗ &nbsp; ${r}</div>`).join('')|| (q?'NO RESULTS — TRY ANOTHER SEARCH.':'')}
// Favorites + toasts
function getFav(){return JSON.parse(localStorage.getItem('dreamGarageFavorites')||'[]')}function toggleFavorite(model){let f=getFav();f=f.includes(model)?f.filter(x=>x!==model):[...f,model];localStorage.setItem('dreamGarageFavorites',JSON.stringify(f));updateFavoriteUI();showToast(f.includes(model)?'Vehicle added to favorites':'Favorite removed',model)}function updateFavoriteUI(){const f=getFav();$('#favoriteHeader span').textContent=f.length;$$('.heart').forEach(h=>{h.classList.toggle('saved',f.includes(h.dataset.model));h.textContent=f.includes(h.dataset.model)?'♥':'♡'})}function showToast(title,text='Your configuration has been updated.'){clearTimeout(toastTimer);$('#toastTitle').textContent=title;$('#toastText').textContent=text;$('#toast').classList.add('show');$('#toast>i').style.animation='none';void $('#toast>i').offsetWidth;$('#toast>i').style.animation='toastProgress 3s linear';toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
// Graph hover, custom cursor, keyboard and easter eggs
$('#performanceGraph').addEventListener('mousemove',e=>{const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,t=$('#graphTooltip');t.style.opacity=1;t.style.left=Math.min(x+14,r.width-125)+'px';t.style.top=Math.max(5,y-55)+'px';t.innerHTML=`RPM: <b>${Math.round(2000+(x/r.width)*7500).toLocaleString()}</b><br>POWER: <b>${Math.round(260+(1-y/r.height)*260)} HP</b>`});$('#performanceGraph').addEventListener('mouseleave',()=>$('#graphTooltip').style.opacity=0);
const cursor=$('#cursor');if(matchMedia('(pointer:fine)').matches){document.body.classList.add('has-cursor');document.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});$$('a,button').forEach(e=>{e.addEventListener('mouseenter',()=>cursor.classList.add('hover'));e.addEventListener('mouseleave',()=>cursor.classList.remove('hover'))});$$('.vehicle-card,.journal-image,.immersive').forEach(e=>{e.addEventListener('mouseenter',()=>cursor.classList.add('image'));e.addEventListener('mouseleave',()=>cursor.classList.remove('image'))})}
let typed='',konami=[],code=[38,38,40,40,37,39,37,39,66,65];document.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal.open').forEach(m=>closeModal(m.id));$('#searchOverlay').classList.remove('open');document.body.style.overflow=''}typed=(typed+e.key).slice(-3);if(typed==='911'){document.body.classList.add('911-mode');showToast('DG-911R mode activated','A sharper state of mind.')}konami.push(e.keyCode);if(konami.length>10)konami.shift();if(konami.join(',')===code.join(',')){document.body.classList.toggle('performance-mode');showToast('TRACK MODE ACTIVATED','Performance theme engaged.')}});
// draggable collection touch support
let dragStart=0;$('#collectionGrid').addEventListener('touchstart',e=>dragStart=e.touches[0].clientX,{passive:true});$('#collectionGrid').addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-dragStart;if(Math.abs(d)>40)carouselMove(d<0?1:-1)},{passive:true});

// Reusable tooltips, magnetic CTAs and desktop drag behaviour
const tip=document.createElement('div');tip.className='floating-tip';document.body.appendChild(tip);function bindTooltip(el,label){el.addEventListener('mouseenter',()=>{tip.textContent=label;tip.classList.add('show')});el.addEventListener('mousemove',e=>{tip.style.left=Math.min(e.clientX+14,innerWidth-180)+'px';tip.style.top=Math.min(e.clientY+18,innerHeight-45)+'px'});el.addEventListener('mouseleave',()=>tip.classList.remove('show'))}$$('[data-tooltip],[data-tip]').forEach(el=>bindTooltip(el,el.dataset.tooltip||el.dataset.tip));
if(matchMedia('(pointer:fine)').matches){$$('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12-3}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});let dragging=false,dragX=0;const grid=$('#collectionGrid');grid.addEventListener('mousedown',e=>{dragging=true;dragX=e.clientX;grid.style.cursor='grabbing';cursor.classList.add('drag')});window.addEventListener('mouseup',()=>{if(!dragging)return;dragging=false;grid.style.cursor='';cursor.classList.remove('drag')});grid.addEventListener('mousemove',e=>{if(!dragging)return;const delta=e.clientX-dragX;if(Math.abs(delta)>55){carouselMove(delta<0?1:-1);dragX=e.clientX}})}
