/* DREAM GARAGE / VANILLA JS — motion, telemetry and editorial interactions */
const $=(selector,parent=document)=>parent.querySelector(selector);
const $$=(selector,parent=document)=>[...parent.querySelectorAll(selector)];
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const vehicleImages={side:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1600&q=88',front:'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1600&q=88',rear:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=88'};
const vehicles=[
  {model:'DG 911R',category:'PURE PERFORMANCE',hp:'518 HP',accel:'3.2 SEC',price:'€ 184,900',image:vehicleImages.side},
  {model:'DG V12',category:'GRAND TOURING',hp:'740 HP',accel:'2.9 SEC',price:'€ 294,500',image:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1400&q=88'},
  {model:'DG GT-X',category:'TRACK BRED',hp:'612 HP',accel:'3.0 SEC',price:'€ 238,900',image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=88'}
];
let toastTimer,carouselIndex=0,viewerIndex=0,rafId=0;

// Loading
let load=0;const loaderTimer=setInterval(()=>{load+=reduceMotion?35:Math.floor(Math.random()*16)+8;if(load>=100){load=100;clearInterval(loaderTimer);setTimeout(()=>$('#loader').classList.add('done'),reduceMotion?0:260)}$('#loaderBar').style.width=load+'%';$('#loaderPercent').textContent=load+'%'},100);

// Navigation and scroll choreography
function closeMobile(){ $('#mobileMenu').classList.remove('open');document.body.classList.remove('menu-open'); }
$('#menuToggle').addEventListener('click',()=>{$('#mobileMenu').classList.add('open');document.body.classList.add('menu-open')});
$('#menuClose').addEventListener('click',closeMobile);$$('.mobile-menu a').forEach(link=>link.addEventListener('click',closeMobile));
const sectionIds=['collection','performance','technology','journal','contact'];
function updateScrollState(){const max=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=(max>0?scrollY/max*100:0)+'%';$('#siteHeader').classList.toggle('scrolled',scrollY>40);$('.scroll-cue').classList.toggle('hide',scrollY>80);const point=scrollY+innerHeight*.35;sectionIds.forEach(id=>{const section=$('#'+id);if(section&&point>=section.offsetTop&&point<section.offsetTop+section.offsetHeight){$$('.nav-link').forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+id))}});}
function parallaxFrame(){rafId=0;const heroImage=$('.hero__image'),immersiveImage=$('.immersive-image');if(reduceMotion)return;if(heroImage)heroImage.style.transform=`translate3d(0,${Math.min(scrollY*.12,70)}px,0) scale(1.08)`;if(immersiveImage){const r=$('#immersive').getBoundingClientRect(),progress=(innerHeight-r.top)/(innerHeight+r.height);immersiveImage.style.transform=`scale(${1.04+Math.max(0,Math.min(1,progress))*.1}) translate3d(0,${(progress-.5)*-32}px,0)`}}
window.addEventListener('scroll',()=>{updateScrollState();if(!rafId)rafId=requestAnimationFrame(parallaxFrame)},{passive:true});updateScrollState();

// Reveal and number counters
function countUp(element){if(element.dataset.counted)return;element.dataset.counted='1';const target=Number(element.dataset.count||element.dataset.target),decimals=Number(element.dataset.decimals||0),start=performance.now();if(reduceMotion){element.textContent=target.toFixed(decimals);return}function tick(now){const progress=Math.min(1,(now-start)/1100),value=target*(1-Math.pow(1-progress,3));element.textContent=value.toFixed(decimals);if(progress<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('visible');if(entry.target.classList.contains('stat-grid'))$$('.stat-number',entry.target).forEach(countUp);if(entry.target.id==='performanceGraph')entry.target.parentElement.classList.add('visible');if(entry.target.classList.contains('live-panel'))startTelemetry();revealObserver.unobserve(entry.target)}),{threshold:.14});
$$('.reveal,.stat-grid,#performanceGraph').forEach((element,index)=>{element.style.transitionDelay=reduceMotion?'0ms':`${Math.min(index%5*70,280)}ms`;revealObserver.observe(element)});setTimeout(()=>$$('.ticker').forEach((element,index)=>setTimeout(()=>countUp(element),index*150+300)),250);

// Collection carousel
function renderCollection(){const grid=$('#collectionGrid');grid.innerHTML=vehicles.map((vehicle,index)=>`<article class="vehicle-card" data-index="${index}" data-story="${vehicle.model}"><div class="vehicle-card__image" style="background-image:url('${vehicle.image}')"></div><button class="heart" data-model="${vehicle.model}" aria-label="Add ${vehicle.model} to favorites">♡</button><div class="vehicle-card__content"><div><small>${vehicle.category}</small><h3>${vehicle.model}</h3><div class="vehicle-card__stats"><span>${vehicle.hp}</span><span>${vehicle.accel}</span><span>${vehicle.price}</span></div></div><b class="card-arrow">↗</b></div></article>`).join('');updateFavoriteUI();$$('.vehicle-card').forEach(card=>card.addEventListener('click',event=>{if(!event.target.closest('.heart'))openViewer(Number(card.dataset.index))}));$$('.heart').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();toggleFavorite(button.dataset.model)}));$('#carouselDots').innerHTML=vehicles.map((_,index)=>`<i class="${index===0?'active':''}" aria-label="Slide ${index+1}"></i>`).join('');}
function carouselMove(direction){carouselIndex=(carouselIndex+direction+vehicles.length)%vehicles.length;const cards=$$('.vehicle-card');if(innerWidth<=700)cards[carouselIndex].scrollIntoView({behavior:reduceMotion?'auto':'smooth',block:'nearest',inline:'center'});else $('#collectionGrid').style.transform=`translateX(${-carouselIndex*8}px)`;$$('#carouselDots i').forEach((dot,index)=>dot.classList.toggle('active',index===carouselIndex));}
$('#prevCar').addEventListener('click',()=>carouselMove(-1));$('#nextCar').addEventListener('click',()=>carouselMove(1));renderCollection();
let dragStart=0,dragging=false;const collectionGrid=$('#collectionGrid');collectionGrid.addEventListener('pointerdown',event=>{dragStart=event.clientX;dragging=true;collectionGrid.setPointerCapture?.(event.pointerId);cursor?.classList.add('drag')});collectionGrid.addEventListener('pointerup',event=>{if(!dragging)return;const distance=event.clientX-dragStart;dragging=false;cursor?.classList.remove('drag');if(Math.abs(distance)>45)carouselMove(distance<0?1:-1)});collectionGrid.addEventListener('pointercancel',()=>{dragging=false;cursor?.classList.remove('drag')});

// Fullscreen vehicle viewer
function openViewer(index=0){viewerIndex=index;updateViewer();$('#viewerModal').classList.add('open');$('#viewerModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(id){const modal=$('#'+id);if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');if(!$('.modal.open')&&!$('#searchOverlay').classList.contains('open')&&!$('#favoritesDrawer').classList.contains('open'))document.body.classList.remove('modal-open')}
function updateViewer(){const vehicle=vehicles[viewerIndex];$('#viewerImage').style.backgroundImage=`url('${vehicle.image}')`;$('#viewerTitle').innerHTML=`${vehicle.model}<br><em>${vehicle.category}.</em>`;$('#viewerView').textContent=vehicle.category}
$('#expandView')?.addEventListener('click',()=>openViewer());$('#viewerPrev').addEventListener('click',()=>{viewerIndex=(viewerIndex+vehicles.length-1)%vehicles.length;updateViewer()});$('#viewerNext').addEventListener('click',()=>{viewerIndex=(viewerIndex+1)%vehicles.length;updateViewer()});$$('[data-close]').forEach(button=>button.addEventListener('click',()=>closeModal(button.dataset.close)));$$('.modal__backdrop').forEach(backdrop=>backdrop.addEventListener('click',()=>closeModal(backdrop.parentElement.id)));

// Favorites with local persistence
function getFavorites(){try{return JSON.parse(localStorage.getItem('dreamGarageFavorites')||'[]')}catch{return[]}}
function toggleFavorite(model){let favorites=getFavorites();favorites=favorites.includes(model)?favorites.filter(item=>item!==model):[...favorites,model];localStorage.setItem('dreamGarageFavorites',JSON.stringify(favorites));updateFavoriteUI();showToast(favorites.includes(model)?'Vehicle added to favorites':'Favorite removed',model)}
function updateFavoriteUI(){const favorites=getFavorites();$('#favoriteHeader span').textContent=favorites.length;$('#favoriteCount').textContent=favorites.length;$$('.heart').forEach(button=>{const saved=favorites.includes(button.dataset.model);button.classList.toggle('saved',saved);button.textContent=saved?'♥':'♡'});$('#favoriteList').innerHTML=favorites.length?favorites.map(model=>{const vehicle=vehicles.find(item=>item.model===model);return`<div class="favorite-row"><div>${model}<small>${vehicle?.category||'DREAM GARAGE'}</small></div><button data-remove-favorite="${model}" aria-label="Remove ${model}">×</button></div>`}).join(''):'<p class="empty-favorites">Your selected machines will appear here.</p>';$$('[data-remove-favorite]').forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.removeFavorite)))}
$('#favoriteHeader').addEventListener('click',()=>{$('#favoritesDrawer').classList.add('open');document.body.classList.add('modal-open');updateFavoriteUI()});$('#favoritesClose').addEventListener('click',()=>closeModal('favoritesDrawer'));

// Live telemetry panel
let telemetryStarted=false;function startTelemetry(){if(telemetryStarted)return;telemetryStarted=true;const rpm=$('#liveRpm'),engineRpm=$('#engineRpm');let value=6420;setInterval(()=>{if(document.hidden)return;value=6420+Math.round(Math.sin(Date.now()/900)*115+Math.sin(Date.now()/210)*24);rpm.textContent=value.toLocaleString();engineRpm.textContent=value.toLocaleString()},1100)}
$('#telemetryBtn').addEventListener('click',()=>showToast('Live feed connected','Track telemetry is streaming in real time.'));

// Search overlay
function openSearch(){$('#searchOverlay').classList.add('open');$('#searchInput').focus();document.body.classList.add('modal-open')}
function closeSearch(){$('#searchOverlay').classList.remove('open');if(!$('.modal.open')&&!$('#favoritesDrawer').classList.contains('open'))document.body.classList.remove('modal-open')}
function renderSearch(query){const q=query.trim().toLowerCase();const results=q?['DG 911R / Pure performance','DG V12 / Grand touring','Active Aerodynamics / Technology','The Science of Speed / Journal','Carbon Monocoque / Technology'].filter(item=>item.toLowerCase().includes(q)||q.length<2):[];$('#searchResults').innerHTML=results.map(result=>`<div>↗ &nbsp; ${result}</div>`).join('')||(q?'NO RESULTS — TRY ANOTHER SEARCH.':'')}
$('#searchBtn').addEventListener('click',openSearch);$('#searchClose').addEventListener('click',closeSearch);$('#searchInput').addEventListener('input',event=>renderSearch(event.target.value));$$('.suggestions button').forEach(button=>button.addEventListener('click',()=>{$('#searchInput').value=button.textContent;renderSearch(button.textContent)}));

// Private drive form and editorial cards
$('#driveBtn').addEventListener('click',()=>{$('#driveModal').classList.add('open');$('#driveModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open')});
$('#driveForm').addEventListener('submit',event=>{event.preventDefault();$('#formContent').innerHTML='<div class="success-state"><p class="eyebrow">REQUEST RECEIVED / 008</p><h2>THE ROAD<br>AWAITS <em>YOU.</em></h2><p>Our concierge team will contact you shortly.</p><button class="button" id="successClose">CLOSE <span>↗</span></button></div>';$('#successClose').addEventListener('click',()=>closeModal('driveModal'));showToast('Request received','Our concierge team will contact you shortly.')});
$$('.journal-card').forEach(card=>card.addEventListener('click',()=>showToast('Story selected',card.dataset.story+' — opening editorial view.')));

// Reusable toast, tooltip and magnetic motion
function showToast(title,text='Your request has been updated.'){clearTimeout(toastTimer);$('#toastTitle').textContent=title;$('#toastText').textContent=text;$('#toast').classList.add('show');const progress=$('#toast>i');progress.style.animation='none';void progress.offsetWidth;progress.style.animation='toastProgress 3s linear';toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
const tooltip=document.createElement('div');tooltip.className='floating-tip';document.body.appendChild(tooltip);function bindTooltip(element,label){element.addEventListener('mouseenter',()=>{tooltip.textContent=label;tooltip.classList.add('show')});element.addEventListener('mousemove',event=>{tooltip.style.left=Math.min(event.clientX+14,innerWidth-185)+'px';tooltip.style.top=Math.min(event.clientY+18,innerHeight-45)+'px'});element.addEventListener('mouseleave',()=>tooltip.classList.remove('show'))}$$('[data-tooltip],[data-tip]').forEach(element=>bindTooltip(element,element.dataset.tooltip||element.dataset.tip));
const cursor=$('#cursor');if(matchMedia('(pointer:fine)').matches){document.body.classList.add('has-cursor');document.addEventListener('mousemove',event=>{cursor.style.left=event.clientX+'px';cursor.style.top=event.clientY+'px'});$$('a,button').forEach(element=>{element.addEventListener('mouseenter',()=>cursor.classList.add('hover'));element.addEventListener('mouseleave',()=>cursor.classList.remove('hover'))});$$('.vehicle-card,.journal-image,.immersive').forEach(element=>{element.addEventListener('mouseenter',()=>cursor.classList.add('image'));element.addEventListener('mouseleave',()=>cursor.classList.remove('image'))});$$('.magnetic').forEach(element=>{element.addEventListener('mousemove',event=>{const rect=element.getBoundingClientRect();element.style.transform=`translate(${(event.clientX-rect.left-rect.width/2)*.12}px,${(event.clientY-rect.top-rect.height/2)*.12-3}px)`});element.addEventListener('mouseleave',()=>element.style.transform='')})}
$$('.bento').forEach(card=>card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect();card.style.setProperty('--mx',`${event.clientX-rect.left}px`);card.style.setProperty('--my',`${event.clientY-rect.top}px`)}));

// Keyboard access and discreet easter eggs
let typed='',konami=[],konamiCode=[38,38,40,40,37,39,37,39,66,65];document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeSearch();closeModal('viewerModal');closeModal('driveModal');closeModal('favoritesDrawer');closeMobile()}if(event.key==='ArrowLeft'&&$('#viewerModal').classList.contains('open'))$('#viewerPrev').click();if(event.key==='ArrowRight'&&$('#viewerModal').classList.contains('open'))$('#viewerNext').click();typed=(typed+event.key).slice(-3);if(typed==='911'){document.body.classList.add('performance-mode');showToast('DG-911R mode activated','A sharper state of mind.')}konami.push(event.keyCode);if(konami.length>10)konami.shift();if(konami.join(',')===konamiCode.join(',')){document.body.classList.toggle('performance-mode');showToast('TRACK MODE ACTIVATED','Performance theme engaged.')}});

updateFavoriteUI();
